# Generated by Django 4.2.5 on 2024-01-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_otp_try",
            field=models.CharField(default=3, max_length=2),
        ),
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_max_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
